export const FETCH_SUGGESTIONS_BEGIN = "FETCH_SUGGESTIONS_BEGIN";
export const FETCH_SUGGESTIONS_SUCCESS = "FETCH_SUGGESTIONS_SUCCESS";
export const FETCH_SUGGESTIONS_FAILURE = "FETCH_SUGGESTIONS_FAILURE";
export const FETCH_BOOKSEARCH_BEGIN = "FETCH_BOOKSEARCH_BEGIN";
export const FETCH_BOOKSEARCH_SUCCESS = "FETCH_BOOKSEARCH_SUCCESS";
export const FETCH_BOOKSEARCH_FAILURE = "FETCH_BOOKSEARCH_FAILURE";
export const CLEAR_BOOKSEARCH_RESULTS = "CLEAR_BOOKSEARCH_RESULTS";
export const ADD_TO_SAVEDBOOKS_LIST = "ADD_TO_SAVEDBOOKS_LIST";
